from src.explainers.counterfactual_based_explainers.counterfactual_explainer_base import CounterfactualExplainerBase
from src.explainers.counterfactual_explanation import CounterfactualExplanation
from typing import Union

class CounterfactualExplainerWrapper:
    """
    Wrapper class for different explainers.
    """

    def __init__(
            self, 
            explainer: CounterfactualExplainerBase,
            num_samples: int,
            counterfactual_target_class: Union[int, str] = "opposite",
        ) -> None:
        """
        Initialize the ExplainerWrapper with a specific explainer.

        Args:
            explainer: The explainer instance to be wrapped.
        """
        self._explainer = explainer
        self.num_samples = num_samples
        self.counterfactual_target_class = counterfactual_target_class

    def explain_local(self, data) -> list[CounterfactualExplanation]:
        """
        Generate explanations for the given data using the wrapped explainer.

        Args:
            model: The model to be explained.
            data: The data for which explanations are to be generated.

        Returns:
            Explanations generated by the wrapped explainer.
        """
        explanation_list = self._explainer.explain_batch(data, self.num_samples, self.counterfactual_target_class)
        return explanation_list 